language: python

python: 3.7

cache:
  pip: true
  directories:
    - ".mypy_cache"
    - ".pytest_cache"

install:
  - python -m pip install --upgrade pip poetry
  - poetry install

script:
  - make lint
  - make tests

after_success:
  - codecov
