name: Continuous integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry install
  linters:
    needs: build
    steps:
    - name: Lint with flake8 and Black
      run: |
        poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
        poetry run black --check .
        poetry run mypy --ignore-missing-imports --disallow-untyped-defs .
  tests:
    needs: build
    steps:
    - name: Test with pytest
      run: |
        poetry run pytest --cov=./ --cov-report=xml
  codecov:
    needs: tests
    steps:
    - name: Upload coverage to Codecov
      run: echo "Codecov disabled"
    # NOTE: Disabled for now
    #   uses: codecov/codecov-action@v1.0.0
    #   with:
    #     token: ${{secrets.CODECOV_TOKEN}}
    #     file: ./coverage.xml
    #     flags: unittests
    #     name: python-aws-ssm
